name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write  # Mandatory for trusted publishing

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for hatch-vcs

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Get version from VERSION file
        id: version
        run: |
          VERSION=$(cat VERSION)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version from file: $VERSION"

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Install hatch
        run: |
          uv tool install hatch

      - name: Install dependencies
        run: |
          uv sync --dev

      - name: Verify version consistency
        run: |
          # Get version from VERSION file
          FILE_VERSION="${{ steps.version.outputs.version }}"
          # Get the release tag from GitHub
          GITHUB_TAG=${GITHUB_REF#refs/tags/}
          echo "Version from file: $FILE_VERSION"
          echo "GitHub release tag: $GITHUB_TAG"
          
          # Strip 'v' prefix from tag if present
          CLEAN_TAG=${GITHUB_TAG#v}
          
          # Check if file version matches the tag exactly
          if [[ "$FILE_VERSION" == "$CLEAN_TAG" ]]; then
            echo "✅ Version consistency verified: $FILE_VERSION"
          else
            echo "❌ Version mismatch! File: $FILE_VERSION, Tag: $CLEAN_TAG"
            echo "Please update the VERSION file to match the release tag"
            exit 1
          fi

      - name: Build release distributions
        run: hatch build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      id-token: write

    environment:
      name: 'pypi'
      url: https://pypi.org/project/open-bedrock-server

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            ## Changes
            
            Please see the [changelog](CHANGELOG.md) for details.
            
            ## PyPI Package
            
            ```bash
            pip install open-bedrock-server==${{ github.ref_name }}
            ```
            
            ## Installation
            
            Visit the [PyPI package page](https://pypi.org/project/open-bedrock-server) for installation instructions.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}